### PR TITLE
Restore support for Python 3 builds

### PR DESCRIPTION
**Pull request by chosak**
Although this project is listed as having Python 3.5 compatible, it doesn't appear to actually be Python 3 compliant. This change adds full support for running DFD using Python 3.6.

It also adds support for modern versions of pip by invoking pip using the command line, rather than the ([now unsupported](https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program)) Python API.

After this change, you can now run DFD from within a Python 3.6 virtual environment in order to create a Python 3.6 build. That build, when expanded, will properly set up and initialize a Python 3.6 virtual environment.

New unit tests have been added that bring coverage to 100% and verify all build/release functionality.

To verify this against cfgov-refresh (assuming its code lives at the same level as this project's code), you can run these commands:

```sh
# From within a virtualenv where you've "pip install -e" this directory:

# Create a build, pulling in local fonts (assuming you have them):
$ no-drama build ../cfgov-refresh/cfgov cfgov current -f -r ../cfgov-refresh/requirements/deployment.txt --static=../cfgov-refresh/static.in/cfgov-fonts

# This should create a local file named cfgov_current.zip.
# Create some dummy files to execute the release flow we use:
$ echo '{"KEY": "VALUE"}' > dummy_environment.json
$ echo '{"static_out": "/path/to/static"}' > dummy_paths.json
$ echo 'print("pre-wsgi.py")' > dummy_prepend_wsgi.py

# Create a release from the build, pulling in those dummy files:
$ no-drama release ./cfgov_current.zip ./dummy_environment.json testing --prepend-wsgi ./dummy_prepend_wsgi.py --paths ./dummy_paths.json

# This should create another local file named cfgov_current_testing.zip.
# Now unzip this file using Python:
$ python cfgov_current_testing.zip

# This will take a LONG time but will eventually unzip the archive,
# set up a virtualenv, and install all Python dependencies.

# Verify the archive by running its virtualenv Python, confirming that 
# Wagtail was installed, and confirming that the environment is being
# properly set from its environment.json file.
$  current/venv/bin/python
Python 3.6.7 (default, Jan 24 2019, 12:16:39) 
...
>>> import wagtail
>>> import os
>>> os.environ['KEY']
'VALUE'
```

### CODE REVIEW

**Comment by rosskarchner** [comment]
Beyond everything you mention above, I really appreciate the thoughtful reorganization of the code!

**Comment by rosskarchner** [comment]
Interesting thing--  `python cfgov_current_testing.zip` keeps failing at:

```
FileExistsError: [Errno 17] File exists: '/Users/karchnerr/projects/drama-free-django/current' -> '/Users/karchnerr/projects/current'
```
Even if I delete `current` before running it.

**Comment by rosskarchner** [comment]
ah-- I think the name 'current' in your example actually gets in the way-- let me try with a different name

**Review by rosskarchner — APPROVED** [review]
Works great!  ~~Do note that naming a build 'current' seems problematic~~

**Comment by rosskarchner** [comment]
It seems like my 'current' problems were caused by an old 'current' directory at a level above DFD and cfgov-refresh, and not a name conflict with the build name.

**Comment by chosak** [comment]
Thanks for the review @rosskarchner. I suspect your 'current' issues were due to the (somewhat unexpected) behavior of the `release` command where it creates a symlink in the parent directory of the one in which you're working.

**Comment by rosskarchner** [comment]
I've opened an issue for that: https://github.com/cfpb/drama-free-django/issues/20

**Pull request merged**
